project_id = "pxxbiouugbhpupzjenpg"

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.chat-export-import]
verify_jwt = false